apiVersion: v1
kind: Pod
metadata:
  name: demo-ms2-pod
  labels:
    app: arc-demo-ms2
    component: arc-component
spec:
  containers:
    - name: demo-ms2
      image: shahankitturn/demo-ms2
      ports:
        - containerPort: 8888